# yaml-language-server: $schema=https://www.schemastore.org/dependabot-2.0.json
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "22:00" # 10pm UTC
    labels:
      - "bot"
      - "dependencies"
      - "go"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "22:00" # 10pm UTC
    labels:
      - "bot"
      - "dependencies"
      - "github-actions"
