blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/cultureamp/terraform-buildkite-plugin/blob/main/README.md
    about: Please check the documentation first
