# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
---
name: pre-release
run-name: pre-release ${{ github.sha }} by @${{ github.actor }}

on:
  # when triggered by pipeline.yml
  workflow_call:
  # when manually triggered
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          # Allow goreleaser to access older tag information.
          fetch-depth: 0

      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: "go.mod"
          cache: true

      - name: Run go-semantic-release
        id: semrel
        uses: go-semantic-release/action@2e9dc4247a6004f8377781bef4cb9dad273a741f # v1.24.1
        with:
          hooks: goreleaser
          dry: true
          allow-initial-development-versions: true
          prerelease: true
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Changelog
        if: steps.semrel.outputs.version != ''
        uses: orhun/git-cliff-action@4a4a951bc43fafe41cd2348d181853f52356bee7 # v4.4.2
        id: git-cliff
        with:
          version: latest
          args: -v --latest --prepend CHANGELOG.md --no-exec # https://git-cliff.org/docs/usage/args
        env:
          GITHUB_REPO: ${{ github.repository }}

      - name: Print version and changelog to logs
        if: steps.semrel.outputs.version != ''
        run: |
          echo "Version: ${{ steps.semrel.outputs.version }}"
          echo "Changelog:"
          echo "${{ steps.git-cliff.outputs.content }}"

      - name: Create or update pre-release PR
        if: steps.semrel.outputs.version != ''
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          add-paths: CHANGELOG.md
          base: pre-release
          branch: main
          commit-message: "chore(release): prepare changelog for ${{ steps.semrel.outputs.version }}"
          title: "chore: prepare release v${{ steps.semrel.outputs.version }}"
          body: |
            :robot: This PR prepares the next release.

            ## Proposed Version: `${{ steps.semrel.outputs.version }}`

            <details><summary>Changelog Details</summary>

            ${{ steps.git-cliff.outputs.content }}
            </details>
